// AUTOGENERATED; DO NOT EDIT
// RUN npm run dataset TO REGENERATE

export const manifest = {
	"meta": {
		"package": "heroicons",
		"version": "2.0.11",
		"created": "2022-09-12T18:53:56.148Z"
	},
	"payload": [
		{
			"kebab": "academic-cap",
			"camel": "academicCap",
			"title": "AcademicCap"
		},
		{
			"kebab": "adjustments-horizontal",
			"camel": "adjustmentsHorizontal",
			"title": "AdjustmentsHorizontal"
		},
		{
			"kebab": "adjustments-vertical",
			"camel": "adjustmentsVertical",
			"title": "AdjustmentsVertical"
		},
		{
			"kebab": "archive-box-arrow-down",
			"camel": "archiveBoxArrowDown",
			"title": "ArchiveBoxArrowDown"
		},
		{
			"kebab": "archive-box-x-mark",
			"camel": "archiveBoxXMark",
			"title": "ArchiveBoxXMark"
		},
		{
			"kebab": "archive-box",
			"camel": "archiveBox",
			"title": "ArchiveBox"
		},
		{
			"kebab": "arrow-down-circle",
			"camel": "arrowDownCircle",
			"title": "ArrowDownCircle"
		},
		{
			"kebab": "arrow-down-left",
			"camel": "arrowDownLeft",
			"title": "ArrowDownLeft"
		},
		{
			"kebab": "arrow-down-on-square-stack",
			"camel": "arrowDownOnSquareStack",
			"title": "ArrowDownOnSquareStack"
		},
		{
			"kebab": "arrow-down-on-square",
			"camel": "arrowDownOnSquare",
			"title": "ArrowDownOnSquare"
		},
		{
			"kebab": "arrow-down-right",
			"camel": "arrowDownRight",
			"title": "ArrowDownRight"
		},
		{
			"kebab": "arrow-down-tray",
			"camel": "arrowDownTray",
			"title": "ArrowDownTray"
		},
		{
			"kebab": "arrow-down",
			"camel": "arrowDown",
			"title": "ArrowDown"
		},
		{
			"kebab": "arrow-left-circle",
			"camel": "arrowLeftCircle",
			"title": "ArrowLeftCircle"
		},
		{
			"kebab": "arrow-left-on-rectangle",
			"camel": "arrowLeftOnRectangle",
			"title": "ArrowLeftOnRectangle"
		},
		{
			"kebab": "arrow-left",
			"camel": "arrowLeft",
			"title": "ArrowLeft"
		},
		{
			"kebab": "arrow-long-down",
			"camel": "arrowLongDown",
			"title": "ArrowLongDown"
		},
		{
			"kebab": "arrow-long-left",
			"camel": "arrowLongLeft",
			"title": "ArrowLongLeft"
		},
		{
			"kebab": "arrow-long-right",
			"camel": "arrowLongRight",
			"title": "ArrowLongRight"
		},
		{
			"kebab": "arrow-long-up",
			"camel": "arrowLongUp",
			"title": "ArrowLongUp"
		},
		{
			"kebab": "arrow-path-rounded-square",
			"camel": "arrowPathRoundedSquare",
			"title": "ArrowPathRoundedSquare"
		},
		{
			"kebab": "arrow-path",
			"camel": "arrowPath",
			"title": "ArrowPath"
		},
		{
			"kebab": "arrow-right-circle",
			"camel": "arrowRightCircle",
			"title": "ArrowRightCircle"
		},
		{
			"kebab": "arrow-right-on-rectangle",
			"camel": "arrowRightOnRectangle",
			"title": "ArrowRightOnRectangle"
		},
		{
			"kebab": "arrow-right",
			"camel": "arrowRight",
			"title": "ArrowRight"
		},
		{
			"kebab": "arrow-small-down",
			"camel": "arrowSmallDown",
			"title": "ArrowSmallDown"
		},
		{
			"kebab": "arrow-small-left",
			"camel": "arrowSmallLeft",
			"title": "ArrowSmallLeft"
		},
		{
			"kebab": "arrow-small-right",
			"camel": "arrowSmallRight",
			"title": "ArrowSmallRight"
		},
		{
			"kebab": "arrow-small-up",
			"camel": "arrowSmallUp",
			"title": "ArrowSmallUp"
		},
		{
			"kebab": "arrow-top-right-on-square",
			"camel": "arrowTopRightOnSquare",
			"title": "ArrowTopRightOnSquare"
		},
		{
			"kebab": "arrow-trending-down",
			"camel": "arrowTrendingDown",
			"title": "ArrowTrendingDown"
		},
		{
			"kebab": "arrow-trending-up",
			"camel": "arrowTrendingUp",
			"title": "ArrowTrendingUp"
		},
		{
			"kebab": "arrow-up-circle",
			"camel": "arrowUpCircle",
			"title": "ArrowUpCircle"
		},
		{
			"kebab": "arrow-up-left",
			"camel": "arrowUpLeft",
			"title": "ArrowUpLeft"
		},
		{
			"kebab": "arrow-up-on-square-stack",
			"camel": "arrowUpOnSquareStack",
			"title": "ArrowUpOnSquareStack"
		},
		{
			"kebab": "arrow-up-on-square",
			"camel": "arrowUpOnSquare",
			"title": "ArrowUpOnSquare"
		},
		{
			"kebab": "arrow-up-right",
			"camel": "arrowUpRight",
			"title": "ArrowUpRight"
		},
		{
			"kebab": "arrow-up-tray",
			"camel": "arrowUpTray",
			"title": "ArrowUpTray"
		},
		{
			"kebab": "arrow-up",
			"camel": "arrowUp",
			"title": "ArrowUp"
		},
		{
			"kebab": "arrow-uturn-down",
			"camel": "arrowUturnDown",
			"title": "ArrowUturnDown"
		},
		{
			"kebab": "arrow-uturn-left",
			"camel": "arrowUturnLeft",
			"title": "ArrowUturnLeft"
		},
		{
			"kebab": "arrow-uturn-right",
			"camel": "arrowUturnRight",
			"title": "ArrowUturnRight"
		},
		{
			"kebab": "arrow-uturn-up",
			"camel": "arrowUturnUp",
			"title": "ArrowUturnUp"
		},
		{
			"kebab": "arrows-pointing-in",
			"camel": "arrowsPointingIn",
			"title": "ArrowsPointingIn"
		},
		{
			"kebab": "arrows-pointing-out",
			"camel": "arrowsPointingOut",
			"title": "ArrowsPointingOut"
		},
		{
			"kebab": "arrows-right-left",
			"camel": "arrowsRightLeft",
			"title": "ArrowsRightLeft"
		},
		{
			"kebab": "arrows-up-down",
			"camel": "arrowsUpDown",
			"title": "ArrowsUpDown"
		},
		{
			"kebab": "at-symbol",
			"camel": "atSymbol",
			"title": "AtSymbol"
		},
		{
			"kebab": "backspace",
			"camel": "backspace",
			"title": "Backspace"
		},
		{
			"kebab": "backward",
			"camel": "backward",
			"title": "Backward"
		},
		{
			"kebab": "banknotes",
			"camel": "banknotes",
			"title": "Banknotes"
		},
		{
			"kebab": "bars-2",
			"camel": "bars2",
			"title": "Bars2"
		},
		{
			"kebab": "bars-3-bottom-left",
			"camel": "bars3BottomLeft",
			"title": "Bars3BottomLeft"
		},
		{
			"kebab": "bars-3-bottom-right",
			"camel": "bars3BottomRight",
			"title": "Bars3BottomRight"
		},
		{
			"kebab": "bars-3-center-left",
			"camel": "bars3CenterLeft",
			"title": "Bars3CenterLeft"
		},
		{
			"kebab": "bars-3",
			"camel": "bars3",
			"title": "Bars3"
		},
		{
			"kebab": "bars-4",
			"camel": "bars4",
			"title": "Bars4"
		},
		{
			"kebab": "bars-arrow-down",
			"camel": "barsArrowDown",
			"title": "BarsArrowDown"
		},
		{
			"kebab": "bars-arrow-up",
			"camel": "barsArrowUp",
			"title": "BarsArrowUp"
		},
		{
			"kebab": "battery-0",
			"camel": "battery0",
			"title": "Battery0"
		},
		{
			"kebab": "battery-100",
			"camel": "battery100",
			"title": "Battery100"
		},
		{
			"kebab": "battery-50",
			"camel": "battery50",
			"title": "Battery50"
		},
		{
			"kebab": "beaker",
			"camel": "beaker",
			"title": "Beaker"
		},
		{
			"kebab": "bell-alert",
			"camel": "bellAlert",
			"title": "BellAlert"
		},
		{
			"kebab": "bell-slash",
			"camel": "bellSlash",
			"title": "BellSlash"
		},
		{
			"kebab": "bell-snooze",
			"camel": "bellSnooze",
			"title": "BellSnooze"
		},
		{
			"kebab": "bell",
			"camel": "bell",
			"title": "Bell"
		},
		{
			"kebab": "bolt-slash",
			"camel": "boltSlash",
			"title": "BoltSlash"
		},
		{
			"kebab": "bolt",
			"camel": "bolt",
			"title": "Bolt"
		},
		{
			"kebab": "book-open",
			"camel": "bookOpen",
			"title": "BookOpen"
		},
		{
			"kebab": "bookmark-slash",
			"camel": "bookmarkSlash",
			"title": "BookmarkSlash"
		},
		{
			"kebab": "bookmark-square",
			"camel": "bookmarkSquare",
			"title": "BookmarkSquare"
		},
		{
			"kebab": "bookmark",
			"camel": "bookmark",
			"title": "Bookmark"
		},
		{
			"kebab": "briefcase",
			"camel": "briefcase",
			"title": "Briefcase"
		},
		{
			"kebab": "bug-ant",
			"camel": "bugAnt",
			"title": "BugAnt"
		},
		{
			"kebab": "building-library",
			"camel": "buildingLibrary",
			"title": "BuildingLibrary"
		},
		{
			"kebab": "building-office-2",
			"camel": "buildingOffice2",
			"title": "BuildingOffice2"
		},
		{
			"kebab": "building-office",
			"camel": "buildingOffice",
			"title": "BuildingOffice"
		},
		{
			"kebab": "building-storefront",
			"camel": "buildingStorefront",
			"title": "BuildingStorefront"
		},
		{
			"kebab": "cake",
			"camel": "cake",
			"title": "Cake"
		},
		{
			"kebab": "calculator",
			"camel": "calculator",
			"title": "Calculator"
		},
		{
			"kebab": "calendar-days",
			"camel": "calendarDays",
			"title": "CalendarDays"
		},
		{
			"kebab": "calendar",
			"camel": "calendar",
			"title": "Calendar"
		},
		{
			"kebab": "camera",
			"camel": "camera",
			"title": "Camera"
		},
		{
			"kebab": "chart-bar-square",
			"camel": "chartBarSquare",
			"title": "ChartBarSquare"
		},
		{
			"kebab": "chart-bar",
			"camel": "chartBar",
			"title": "ChartBar"
		},
		{
			"kebab": "chart-pie",
			"camel": "chartPie",
			"title": "ChartPie"
		},
		{
			"kebab": "chat-bubble-bottom-center-text",
			"camel": "chatBubbleBottomCenterText",
			"title": "ChatBubbleBottomCenterText"
		},
		{
			"kebab": "chat-bubble-bottom-center",
			"camel": "chatBubbleBottomCenter",
			"title": "ChatBubbleBottomCenter"
		},
		{
			"kebab": "chat-bubble-left-ellipsis",
			"camel": "chatBubbleLeftEllipsis",
			"title": "ChatBubbleLeftEllipsis"
		},
		{
			"kebab": "chat-bubble-left-right",
			"camel": "chatBubbleLeftRight",
			"title": "ChatBubbleLeftRight"
		},
		{
			"kebab": "chat-bubble-left",
			"camel": "chatBubbleLeft",
			"title": "ChatBubbleLeft"
		},
		{
			"kebab": "chat-bubble-oval-left-ellipsis",
			"camel": "chatBubbleOvalLeftEllipsis",
			"title": "ChatBubbleOvalLeftEllipsis"
		},
		{
			"kebab": "chat-bubble-oval-left",
			"camel": "chatBubbleOvalLeft",
			"title": "ChatBubbleOvalLeft"
		},
		{
			"kebab": "check-badge",
			"camel": "checkBadge",
			"title": "CheckBadge"
		},
		{
			"kebab": "check-circle",
			"camel": "checkCircle",
			"title": "CheckCircle"
		},
		{
			"kebab": "check",
			"camel": "check",
			"title": "Check"
		},
		{
			"kebab": "chevron-double-down",
			"camel": "chevronDoubleDown",
			"title": "ChevronDoubleDown"
		},
		{
			"kebab": "chevron-double-left",
			"camel": "chevronDoubleLeft",
			"title": "ChevronDoubleLeft"
		},
		{
			"kebab": "chevron-double-right",
			"camel": "chevronDoubleRight",
			"title": "ChevronDoubleRight"
		},
		{
			"kebab": "chevron-double-up",
			"camel": "chevronDoubleUp",
			"title": "ChevronDoubleUp"
		},
		{
			"kebab": "chevron-down",
			"camel": "chevronDown",
			"title": "ChevronDown"
		},
		{
			"kebab": "chevron-left",
			"camel": "chevronLeft",
			"title": "ChevronLeft"
		},
		{
			"kebab": "chevron-right",
			"camel": "chevronRight",
			"title": "ChevronRight"
		},
		{
			"kebab": "chevron-up-down",
			"camel": "chevronUpDown",
			"title": "ChevronUpDown"
		},
		{
			"kebab": "chevron-up",
			"camel": "chevronUp",
			"title": "ChevronUp"
		},
		{
			"kebab": "circle-stack",
			"camel": "circleStack",
			"title": "CircleStack"
		},
		{
			"kebab": "clipboard-document-check",
			"camel": "clipboardDocumentCheck",
			"title": "ClipboardDocumentCheck"
		},
		{
			"kebab": "clipboard-document-list",
			"camel": "clipboardDocumentList",
			"title": "ClipboardDocumentList"
		},
		{
			"kebab": "clipboard-document",
			"camel": "clipboardDocument",
			"title": "ClipboardDocument"
		},
		{
			"kebab": "clipboard",
			"camel": "clipboard",
			"title": "Clipboard"
		},
		{
			"kebab": "clock",
			"camel": "clock",
			"title": "Clock"
		},
		{
			"kebab": "cloud-arrow-down",
			"camel": "cloudArrowDown",
			"title": "CloudArrowDown"
		},
		{
			"kebab": "cloud-arrow-up",
			"camel": "cloudArrowUp",
			"title": "CloudArrowUp"
		},
		{
			"kebab": "cloud",
			"camel": "cloud",
			"title": "Cloud"
		},
		{
			"kebab": "code-bracket-square",
			"camel": "codeBracketSquare",
			"title": "CodeBracketSquare"
		},
		{
			"kebab": "code-bracket",
			"camel": "codeBracket",
			"title": "CodeBracket"
		},
		{
			"kebab": "cog-6-tooth",
			"camel": "cog6Tooth",
			"title": "Cog6Tooth"
		},
		{
			"kebab": "cog-8-tooth",
			"camel": "cog8Tooth",
			"title": "Cog8Tooth"
		},
		{
			"kebab": "cog",
			"camel": "cog",
			"title": "Cog"
		},
		{
			"kebab": "command-line",
			"camel": "commandLine",
			"title": "CommandLine"
		},
		{
			"kebab": "computer-desktop",
			"camel": "computerDesktop",
			"title": "ComputerDesktop"
		},
		{
			"kebab": "cpu-chip",
			"camel": "cpuChip",
			"title": "CpuChip"
		},
		{
			"kebab": "credit-card",
			"camel": "creditCard",
			"title": "CreditCard"
		},
		{
			"kebab": "cube-transparent",
			"camel": "cubeTransparent",
			"title": "CubeTransparent"
		},
		{
			"kebab": "cube",
			"camel": "cube",
			"title": "Cube"
		},
		{
			"kebab": "currency-bangladeshi",
			"camel": "currencyBangladeshi",
			"title": "CurrencyBangladeshi"
		},
		{
			"kebab": "currency-dollar",
			"camel": "currencyDollar",
			"title": "CurrencyDollar"
		},
		{
			"kebab": "currency-euro",
			"camel": "currencyEuro",
			"title": "CurrencyEuro"
		},
		{
			"kebab": "currency-pound",
			"camel": "currencyPound",
			"title": "CurrencyPound"
		},
		{
			"kebab": "currency-rupee",
			"camel": "currencyRupee",
			"title": "CurrencyRupee"
		},
		{
			"kebab": "currency-yen",
			"camel": "currencyYen",
			"title": "CurrencyYen"
		},
		{
			"kebab": "cursor-arrow-rays",
			"camel": "cursorArrowRays",
			"title": "CursorArrowRays"
		},
		{
			"kebab": "cursor-arrow-ripple",
			"camel": "cursorArrowRipple",
			"title": "CursorArrowRipple"
		},
		{
			"kebab": "device-phone-mobile",
			"camel": "devicePhoneMobile",
			"title": "DevicePhoneMobile"
		},
		{
			"kebab": "device-tablet",
			"camel": "deviceTablet",
			"title": "DeviceTablet"
		},
		{
			"kebab": "document-arrow-down",
			"camel": "documentArrowDown",
			"title": "DocumentArrowDown"
		},
		{
			"kebab": "document-arrow-up",
			"camel": "documentArrowUp",
			"title": "DocumentArrowUp"
		},
		{
			"kebab": "document-chart-bar",
			"camel": "documentChartBar",
			"title": "DocumentChartBar"
		},
		{
			"kebab": "document-check",
			"camel": "documentCheck",
			"title": "DocumentCheck"
		},
		{
			"kebab": "document-duplicate",
			"camel": "documentDuplicate",
			"title": "DocumentDuplicate"
		},
		{
			"kebab": "document-magnifying-glass",
			"camel": "documentMagnifyingGlass",
			"title": "DocumentMagnifyingGlass"
		},
		{
			"kebab": "document-minus",
			"camel": "documentMinus",
			"title": "DocumentMinus"
		},
		{
			"kebab": "document-plus",
			"camel": "documentPlus",
			"title": "DocumentPlus"
		},
		{
			"kebab": "document-text",
			"camel": "documentText",
			"title": "DocumentText"
		},
		{
			"kebab": "document",
			"camel": "document",
			"title": "Document"
		},
		{
			"kebab": "ellipsis-horizontal-circle",
			"camel": "ellipsisHorizontalCircle",
			"title": "EllipsisHorizontalCircle"
		},
		{
			"kebab": "ellipsis-horizontal",
			"camel": "ellipsisHorizontal",
			"title": "EllipsisHorizontal"
		},
		{
			"kebab": "ellipsis-vertical",
			"camel": "ellipsisVertical",
			"title": "EllipsisVertical"
		},
		{
			"kebab": "envelope-open",
			"camel": "envelopeOpen",
			"title": "EnvelopeOpen"
		},
		{
			"kebab": "envelope",
			"camel": "envelope",
			"title": "Envelope"
		},
		{
			"kebab": "exclamation-circle",
			"camel": "exclamationCircle",
			"title": "ExclamationCircle"
		},
		{
			"kebab": "exclamation-triangle",
			"camel": "exclamationTriangle",
			"title": "ExclamationTriangle"
		},
		{
			"kebab": "eye-dropper",
			"camel": "eyeDropper",
			"title": "EyeDropper"
		},
		{
			"kebab": "eye-slash",
			"camel": "eyeSlash",
			"title": "EyeSlash"
		},
		{
			"kebab": "eye",
			"camel": "eye",
			"title": "Eye"
		},
		{
			"kebab": "face-frown",
			"camel": "faceFrown",
			"title": "FaceFrown"
		},
		{
			"kebab": "face-smile",
			"camel": "faceSmile",
			"title": "FaceSmile"
		},
		{
			"kebab": "film",
			"camel": "film",
			"title": "Film"
		},
		{
			"kebab": "finger-print",
			"camel": "fingerPrint",
			"title": "FingerPrint"
		},
		{
			"kebab": "fire",
			"camel": "fire",
			"title": "Fire"
		},
		{
			"kebab": "flag",
			"camel": "flag",
			"title": "Flag"
		},
		{
			"kebab": "folder-arrow-down",
			"camel": "folderArrowDown",
			"title": "FolderArrowDown"
		},
		{
			"kebab": "folder-minus",
			"camel": "folderMinus",
			"title": "FolderMinus"
		},
		{
			"kebab": "folder-open",
			"camel": "folderOpen",
			"title": "FolderOpen"
		},
		{
			"kebab": "folder-plus",
			"camel": "folderPlus",
			"title": "FolderPlus"
		},
		{
			"kebab": "folder",
			"camel": "folder",
			"title": "Folder"
		},
		{
			"kebab": "forward",
			"camel": "forward",
			"title": "Forward"
		},
		{
			"kebab": "funnel",
			"camel": "funnel",
			"title": "Funnel"
		},
		{
			"kebab": "gif",
			"camel": "gif",
			"title": "Gif"
		},
		{
			"kebab": "gift-top",
			"camel": "giftTop",
			"title": "GiftTop"
		},
		{
			"kebab": "gift",
			"camel": "gift",
			"title": "Gift"
		},
		{
			"kebab": "globe-alt",
			"camel": "globeAlt",
			"title": "GlobeAlt"
		},
		{
			"kebab": "globe-americas",
			"camel": "globeAmericas",
			"title": "GlobeAmericas"
		},
		{
			"kebab": "globe-asia-australia",
			"camel": "globeAsiaAustralia",
			"title": "GlobeAsiaAustralia"
		},
		{
			"kebab": "globe-europe-africa",
			"camel": "globeEuropeAfrica",
			"title": "GlobeEuropeAfrica"
		},
		{
			"kebab": "hand-raised",
			"camel": "handRaised",
			"title": "HandRaised"
		},
		{
			"kebab": "hand-thumb-down",
			"camel": "handThumbDown",
			"title": "HandThumbDown"
		},
		{
			"kebab": "hand-thumb-up",
			"camel": "handThumbUp",
			"title": "HandThumbUp"
		},
		{
			"kebab": "hashtag",
			"camel": "hashtag",
			"title": "Hashtag"
		},
		{
			"kebab": "heart",
			"camel": "heart",
			"title": "Heart"
		},
		{
			"kebab": "home-modern",
			"camel": "homeModern",
			"title": "HomeModern"
		},
		{
			"kebab": "home",
			"camel": "home",
			"title": "Home"
		},
		{
			"kebab": "identification",
			"camel": "identification",
			"title": "Identification"
		},
		{
			"kebab": "inbox-arrow-down",
			"camel": "inboxArrowDown",
			"title": "InboxArrowDown"
		},
		{
			"kebab": "inbox-stack",
			"camel": "inboxStack",
			"title": "InboxStack"
		},
		{
			"kebab": "inbox",
			"camel": "inbox",
			"title": "Inbox"
		},
		{
			"kebab": "information-circle",
			"camel": "informationCircle",
			"title": "InformationCircle"
		},
		{
			"kebab": "key",
			"camel": "key",
			"title": "Key"
		},
		{
			"kebab": "language",
			"camel": "language",
			"title": "Language"
		},
		{
			"kebab": "lifebuoy",
			"camel": "lifebuoy",
			"title": "Lifebuoy"
		},
		{
			"kebab": "light-bulb",
			"camel": "lightBulb",
			"title": "LightBulb"
		},
		{
			"kebab": "link",
			"camel": "link",
			"title": "Link"
		},
		{
			"kebab": "list-bullet",
			"camel": "listBullet",
			"title": "ListBullet"
		},
		{
			"kebab": "lock-closed",
			"camel": "lockClosed",
			"title": "LockClosed"
		},
		{
			"kebab": "lock-open",
			"camel": "lockOpen",
			"title": "LockOpen"
		},
		{
			"kebab": "magnifying-glass-circle",
			"camel": "magnifyingGlassCircle",
			"title": "MagnifyingGlassCircle"
		},
		{
			"kebab": "magnifying-glass-minus",
			"camel": "magnifyingGlassMinus",
			"title": "MagnifyingGlassMinus"
		},
		{
			"kebab": "magnifying-glass-plus",
			"camel": "magnifyingGlassPlus",
			"title": "MagnifyingGlassPlus"
		},
		{
			"kebab": "magnifying-glass",
			"camel": "magnifyingGlass",
			"title": "MagnifyingGlass"
		},
		{
			"kebab": "map-pin",
			"camel": "mapPin",
			"title": "MapPin"
		},
		{
			"kebab": "map",
			"camel": "map",
			"title": "Map"
		},
		{
			"kebab": "megaphone",
			"camel": "megaphone",
			"title": "Megaphone"
		},
		{
			"kebab": "microphone",
			"camel": "microphone",
			"title": "Microphone"
		},
		{
			"kebab": "minus-circle",
			"camel": "minusCircle",
			"title": "MinusCircle"
		},
		{
			"kebab": "minus-small",
			"camel": "minusSmall",
			"title": "MinusSmall"
		},
		{
			"kebab": "minus",
			"camel": "minus",
			"title": "Minus"
		},
		{
			"kebab": "moon",
			"camel": "moon",
			"title": "Moon"
		},
		{
			"kebab": "musical-note",
			"camel": "musicalNote",
			"title": "MusicalNote"
		},
		{
			"kebab": "newspaper",
			"camel": "newspaper",
			"title": "Newspaper"
		},
		{
			"kebab": "no-symbol",
			"camel": "noSymbol",
			"title": "NoSymbol"
		},
		{
			"kebab": "paint-brush",
			"camel": "paintBrush",
			"title": "PaintBrush"
		},
		{
			"kebab": "paper-airplane",
			"camel": "paperAirplane",
			"title": "PaperAirplane"
		},
		{
			"kebab": "paper-clip",
			"camel": "paperClip",
			"title": "PaperClip"
		},
		{
			"kebab": "pause-circle",
			"camel": "pauseCircle",
			"title": "PauseCircle"
		},
		{
			"kebab": "pause",
			"camel": "pause",
			"title": "Pause"
		},
		{
			"kebab": "pencil-square",
			"camel": "pencilSquare",
			"title": "PencilSquare"
		},
		{
			"kebab": "pencil",
			"camel": "pencil",
			"title": "Pencil"
		},
		{
			"kebab": "phone-arrow-down-left",
			"camel": "phoneArrowDownLeft",
			"title": "PhoneArrowDownLeft"
		},
		{
			"kebab": "phone-arrow-up-right",
			"camel": "phoneArrowUpRight",
			"title": "PhoneArrowUpRight"
		},
		{
			"kebab": "phone-x-mark",
			"camel": "phoneXMark",
			"title": "PhoneXMark"
		},
		{
			"kebab": "phone",
			"camel": "phone",
			"title": "Phone"
		},
		{
			"kebab": "photo",
			"camel": "photo",
			"title": "Photo"
		},
		{
			"kebab": "play-circle",
			"camel": "playCircle",
			"title": "PlayCircle"
		},
		{
			"kebab": "play-pause",
			"camel": "playPause",
			"title": "PlayPause"
		},
		{
			"kebab": "play",
			"camel": "play",
			"title": "Play"
		},
		{
			"kebab": "plus-circle",
			"camel": "plusCircle",
			"title": "PlusCircle"
		},
		{
			"kebab": "plus-small",
			"camel": "plusSmall",
			"title": "PlusSmall"
		},
		{
			"kebab": "plus",
			"camel": "plus",
			"title": "Plus"
		},
		{
			"kebab": "power",
			"camel": "power",
			"title": "Power"
		},
		{
			"kebab": "presentation-chart-bar",
			"camel": "presentationChartBar",
			"title": "PresentationChartBar"
		},
		{
			"kebab": "presentation-chart-line",
			"camel": "presentationChartLine",
			"title": "PresentationChartLine"
		},
		{
			"kebab": "printer",
			"camel": "printer",
			"title": "Printer"
		},
		{
			"kebab": "puzzle-piece",
			"camel": "puzzlePiece",
			"title": "PuzzlePiece"
		},
		{
			"kebab": "qr-code",
			"camel": "qrCode",
			"title": "QrCode"
		},
		{
			"kebab": "question-mark-circle",
			"camel": "questionMarkCircle",
			"title": "QuestionMarkCircle"
		},
		{
			"kebab": "queue-list",
			"camel": "queueList",
			"title": "QueueList"
		},
		{
			"kebab": "radio",
			"camel": "radio",
			"title": "Radio"
		},
		{
			"kebab": "receipt-percent",
			"camel": "receiptPercent",
			"title": "ReceiptPercent"
		},
		{
			"kebab": "receipt-refund",
			"camel": "receiptRefund",
			"title": "ReceiptRefund"
		},
		{
			"kebab": "rectangle-group",
			"camel": "rectangleGroup",
			"title": "RectangleGroup"
		},
		{
			"kebab": "rectangle-stack",
			"camel": "rectangleStack",
			"title": "RectangleStack"
		},
		{
			"kebab": "rocket-launch",
			"camel": "rocketLaunch",
			"title": "RocketLaunch"
		},
		{
			"kebab": "rss",
			"camel": "rss",
			"title": "Rss"
		},
		{
			"kebab": "scale",
			"camel": "scale",
			"title": "Scale"
		},
		{
			"kebab": "scissors",
			"camel": "scissors",
			"title": "Scissors"
		},
		{
			"kebab": "server-stack",
			"camel": "serverStack",
			"title": "ServerStack"
		},
		{
			"kebab": "server",
			"camel": "server",
			"title": "Server"
		},
		{
			"kebab": "share",
			"camel": "share",
			"title": "Share"
		},
		{
			"kebab": "shield-check",
			"camel": "shieldCheck",
			"title": "ShieldCheck"
		},
		{
			"kebab": "shield-exclamation",
			"camel": "shieldExclamation",
			"title": "ShieldExclamation"
		},
		{
			"kebab": "shopping-bag",
			"camel": "shoppingBag",
			"title": "ShoppingBag"
		},
		{
			"kebab": "shopping-cart",
			"camel": "shoppingCart",
			"title": "ShoppingCart"
		},
		{
			"kebab": "signal-slash",
			"camel": "signalSlash",
			"title": "SignalSlash"
		},
		{
			"kebab": "signal",
			"camel": "signal",
			"title": "Signal"
		},
		{
			"kebab": "sparkles",
			"camel": "sparkles",
			"title": "Sparkles"
		},
		{
			"kebab": "speaker-wave",
			"camel": "speakerWave",
			"title": "SpeakerWave"
		},
		{
			"kebab": "speaker-x-mark",
			"camel": "speakerXMark",
			"title": "SpeakerXMark"
		},
		{
			"kebab": "square-2-stack",
			"camel": "square2Stack",
			"title": "Square2Stack"
		},
		{
			"kebab": "square-3-stack-3d",
			"camel": "square3Stack3d",
			"title": "Square3Stack3d"
		},
		{
			"kebab": "squares-2x2",
			"camel": "squares2x2",
			"title": "Squares2x2"
		},
		{
			"kebab": "squares-plus",
			"camel": "squaresPlus",
			"title": "SquaresPlus"
		},
		{
			"kebab": "star",
			"camel": "star",
			"title": "Star"
		},
		{
			"kebab": "stop-circle",
			"camel": "stopCircle",
			"title": "StopCircle"
		},
		{
			"kebab": "stop",
			"camel": "stop",
			"title": "Stop"
		},
		{
			"kebab": "sun",
			"camel": "sun",
			"title": "Sun"
		},
		{
			"kebab": "swatch",
			"camel": "swatch",
			"title": "Swatch"
		},
		{
			"kebab": "table-cells",
			"camel": "tableCells",
			"title": "TableCells"
		},
		{
			"kebab": "tag",
			"camel": "tag",
			"title": "Tag"
		},
		{
			"kebab": "ticket",
			"camel": "ticket",
			"title": "Ticket"
		},
		{
			"kebab": "trash",
			"camel": "trash",
			"title": "Trash"
		},
		{
			"kebab": "trophy",
			"camel": "trophy",
			"title": "Trophy"
		},
		{
			"kebab": "truck",
			"camel": "truck",
			"title": "Truck"
		},
		{
			"kebab": "tv",
			"camel": "tv",
			"title": "Tv"
		},
		{
			"kebab": "user-circle",
			"camel": "userCircle",
			"title": "UserCircle"
		},
		{
			"kebab": "user-group",
			"camel": "userGroup",
			"title": "UserGroup"
		},
		{
			"kebab": "user-minus",
			"camel": "userMinus",
			"title": "UserMinus"
		},
		{
			"kebab": "user-plus",
			"camel": "userPlus",
			"title": "UserPlus"
		},
		{
			"kebab": "user",
			"camel": "user",
			"title": "User"
		},
		{
			"kebab": "users",
			"camel": "users",
			"title": "Users"
		},
		{
			"kebab": "variable",
			"camel": "variable",
			"title": "Variable"
		},
		{
			"kebab": "video-camera-slash",
			"camel": "videoCameraSlash",
			"title": "VideoCameraSlash"
		},
		{
			"kebab": "video-camera",
			"camel": "videoCamera",
			"title": "VideoCamera"
		},
		{
			"kebab": "view-columns",
			"camel": "viewColumns",
			"title": "ViewColumns"
		},
		{
			"kebab": "viewfinder-circle",
			"camel": "viewfinderCircle",
			"title": "ViewfinderCircle"
		},
		{
			"kebab": "wallet",
			"camel": "wallet",
			"title": "Wallet"
		},
		{
			"kebab": "wifi",
			"camel": "wifi",
			"title": "Wifi"
		},
		{
			"kebab": "window",
			"camel": "window",
			"title": "Window"
		},
		{
			"kebab": "wrench-screwdriver",
			"camel": "wrenchScrewdriver",
			"title": "WrenchScrewdriver"
		},
		{
			"kebab": "wrench",
			"camel": "wrench",
			"title": "Wrench"
		},
		{
			"kebab": "x-circle",
			"camel": "xCircle",
			"title": "XCircle"
		},
		{
			"kebab": "x-mark",
			"camel": "xMark",
			"title": "XMark"
		}
	]
}
