// AUTOGENERATED; DO NOT EDIT
// RUN npm run dataset TO REGENERATE

export const manifest = {
	"meta": {
		"package": "heroicons",
		"version": "1.0.6",
		"created": "2022-03-02T11:41:46.838Z"
	},
	"payload": [
		{
			"kebab": "academic-cap",
			"camel": "academicCap",
			"title": "AcademicCap"
		},
		{
			"kebab": "adjustments",
			"camel": "adjustments",
			"title": "Adjustments"
		},
		{
			"kebab": "annotation",
			"camel": "annotation",
			"title": "Annotation"
		},
		{
			"kebab": "archive",
			"camel": "archive",
			"title": "Archive"
		},
		{
			"kebab": "arrow-circle-down",
			"camel": "arrowCircleDown",
			"title": "ArrowCircleDown"
		},
		{
			"kebab": "arrow-circle-left",
			"camel": "arrowCircleLeft",
			"title": "ArrowCircleLeft"
		},
		{
			"kebab": "arrow-circle-right",
			"camel": "arrowCircleRight",
			"title": "ArrowCircleRight"
		},
		{
			"kebab": "arrow-circle-up",
			"camel": "arrowCircleUp",
			"title": "ArrowCircleUp"
		},
		{
			"kebab": "arrow-down",
			"camel": "arrowDown",
			"title": "ArrowDown"
		},
		{
			"kebab": "arrow-left",
			"camel": "arrowLeft",
			"title": "ArrowLeft"
		},
		{
			"kebab": "arrow-narrow-down",
			"camel": "arrowNarrowDown",
			"title": "ArrowNarrowDown"
		},
		{
			"kebab": "arrow-narrow-left",
			"camel": "arrowNarrowLeft",
			"title": "ArrowNarrowLeft"
		},
		{
			"kebab": "arrow-narrow-right",
			"camel": "arrowNarrowRight",
			"title": "ArrowNarrowRight"
		},
		{
			"kebab": "arrow-narrow-up",
			"camel": "arrowNarrowUp",
			"title": "ArrowNarrowUp"
		},
		{
			"kebab": "arrow-right",
			"camel": "arrowRight",
			"title": "ArrowRight"
		},
		{
			"kebab": "arrow-sm-down",
			"camel": "arrowSmDown",
			"title": "ArrowSmDown"
		},
		{
			"kebab": "arrow-sm-left",
			"camel": "arrowSmLeft",
			"title": "ArrowSmLeft"
		},
		{
			"kebab": "arrow-sm-right",
			"camel": "arrowSmRight",
			"title": "ArrowSmRight"
		},
		{
			"kebab": "arrow-sm-up",
			"camel": "arrowSmUp",
			"title": "ArrowSmUp"
		},
		{
			"kebab": "arrow-up",
			"camel": "arrowUp",
			"title": "ArrowUp"
		},
		{
			"kebab": "arrows-expand",
			"camel": "arrowsExpand",
			"title": "ArrowsExpand"
		},
		{
			"kebab": "at-symbol",
			"camel": "atSymbol",
			"title": "AtSymbol"
		},
		{
			"kebab": "backspace",
			"camel": "backspace",
			"title": "Backspace"
		},
		{
			"kebab": "badge-check",
			"camel": "badgeCheck",
			"title": "BadgeCheck"
		},
		{
			"kebab": "ban",
			"camel": "ban",
			"title": "Ban"
		},
		{
			"kebab": "beaker",
			"camel": "beaker",
			"title": "Beaker"
		},
		{
			"kebab": "bell",
			"camel": "bell",
			"title": "Bell"
		},
		{
			"kebab": "book-open",
			"camel": "bookOpen",
			"title": "BookOpen"
		},
		{
			"kebab": "bookmark-alt",
			"camel": "bookmarkAlt",
			"title": "BookmarkAlt"
		},
		{
			"kebab": "bookmark",
			"camel": "bookmark",
			"title": "Bookmark"
		},
		{
			"kebab": "briefcase",
			"camel": "briefcase",
			"title": "Briefcase"
		},
		{
			"kebab": "cake",
			"camel": "cake",
			"title": "Cake"
		},
		{
			"kebab": "calculator",
			"camel": "calculator",
			"title": "Calculator"
		},
		{
			"kebab": "calendar",
			"camel": "calendar",
			"title": "Calendar"
		},
		{
			"kebab": "camera",
			"camel": "camera",
			"title": "Camera"
		},
		{
			"kebab": "cash",
			"camel": "cash",
			"title": "Cash"
		},
		{
			"kebab": "chart-bar",
			"camel": "chartBar",
			"title": "ChartBar"
		},
		{
			"kebab": "chart-pie",
			"camel": "chartPie",
			"title": "ChartPie"
		},
		{
			"kebab": "chart-square-bar",
			"camel": "chartSquareBar",
			"title": "ChartSquareBar"
		},
		{
			"kebab": "chat-alt-2",
			"camel": "chatAlt2",
			"title": "ChatAlt2"
		},
		{
			"kebab": "chat-alt",
			"camel": "chatAlt",
			"title": "ChatAlt"
		},
		{
			"kebab": "chat",
			"camel": "chat",
			"title": "Chat"
		},
		{
			"kebab": "check-circle",
			"camel": "checkCircle",
			"title": "CheckCircle"
		},
		{
			"kebab": "check",
			"camel": "check",
			"title": "Check"
		},
		{
			"kebab": "chevron-double-down",
			"camel": "chevronDoubleDown",
			"title": "ChevronDoubleDown"
		},
		{
			"kebab": "chevron-double-left",
			"camel": "chevronDoubleLeft",
			"title": "ChevronDoubleLeft"
		},
		{
			"kebab": "chevron-double-right",
			"camel": "chevronDoubleRight",
			"title": "ChevronDoubleRight"
		},
		{
			"kebab": "chevron-double-up",
			"camel": "chevronDoubleUp",
			"title": "ChevronDoubleUp"
		},
		{
			"kebab": "chevron-down",
			"camel": "chevronDown",
			"title": "ChevronDown"
		},
		{
			"kebab": "chevron-left",
			"camel": "chevronLeft",
			"title": "ChevronLeft"
		},
		{
			"kebab": "chevron-right",
			"camel": "chevronRight",
			"title": "ChevronRight"
		},
		{
			"kebab": "chevron-up",
			"camel": "chevronUp",
			"title": "ChevronUp"
		},
		{
			"kebab": "chip",
			"camel": "chip",
			"title": "Chip"
		},
		{
			"kebab": "clipboard-check",
			"camel": "clipboardCheck",
			"title": "ClipboardCheck"
		},
		{
			"kebab": "clipboard-copy",
			"camel": "clipboardCopy",
			"title": "ClipboardCopy"
		},
		{
			"kebab": "clipboard-list",
			"camel": "clipboardList",
			"title": "ClipboardList"
		},
		{
			"kebab": "clipboard",
			"camel": "clipboard",
			"title": "Clipboard"
		},
		{
			"kebab": "clock",
			"camel": "clock",
			"title": "Clock"
		},
		{
			"kebab": "cloud-download",
			"camel": "cloudDownload",
			"title": "CloudDownload"
		},
		{
			"kebab": "cloud-upload",
			"camel": "cloudUpload",
			"title": "CloudUpload"
		},
		{
			"kebab": "cloud",
			"camel": "cloud",
			"title": "Cloud"
		},
		{
			"kebab": "code",
			"camel": "code",
			"title": "Code"
		},
		{
			"kebab": "cog",
			"camel": "cog",
			"title": "Cog"
		},
		{
			"kebab": "collection",
			"camel": "collection",
			"title": "Collection"
		},
		{
			"kebab": "color-swatch",
			"camel": "colorSwatch",
			"title": "ColorSwatch"
		},
		{
			"kebab": "credit-card",
			"camel": "creditCard",
			"title": "CreditCard"
		},
		{
			"kebab": "cube-transparent",
			"camel": "cubeTransparent",
			"title": "CubeTransparent"
		},
		{
			"kebab": "cube",
			"camel": "cube",
			"title": "Cube"
		},
		{
			"kebab": "currency-bangladeshi",
			"camel": "currencyBangladeshi",
			"title": "CurrencyBangladeshi"
		},
		{
			"kebab": "currency-dollar",
			"camel": "currencyDollar",
			"title": "CurrencyDollar"
		},
		{
			"kebab": "currency-euro",
			"camel": "currencyEuro",
			"title": "CurrencyEuro"
		},
		{
			"kebab": "currency-pound",
			"camel": "currencyPound",
			"title": "CurrencyPound"
		},
		{
			"kebab": "currency-rupee",
			"camel": "currencyRupee",
			"title": "CurrencyRupee"
		},
		{
			"kebab": "currency-yen",
			"camel": "currencyYen",
			"title": "CurrencyYen"
		},
		{
			"kebab": "cursor-click",
			"camel": "cursorClick",
			"title": "CursorClick"
		},
		{
			"kebab": "database",
			"camel": "database",
			"title": "Database"
		},
		{
			"kebab": "desktop-computer",
			"camel": "desktopComputer",
			"title": "DesktopComputer"
		},
		{
			"kebab": "device-mobile",
			"camel": "deviceMobile",
			"title": "DeviceMobile"
		},
		{
			"kebab": "device-tablet",
			"camel": "deviceTablet",
			"title": "DeviceTablet"
		},
		{
			"kebab": "document-add",
			"camel": "documentAdd",
			"title": "DocumentAdd"
		},
		{
			"kebab": "document-download",
			"camel": "documentDownload",
			"title": "DocumentDownload"
		},
		{
			"kebab": "document-duplicate",
			"camel": "documentDuplicate",
			"title": "DocumentDuplicate"
		},
		{
			"kebab": "document-remove",
			"camel": "documentRemove",
			"title": "DocumentRemove"
		},
		{
			"kebab": "document-report",
			"camel": "documentReport",
			"title": "DocumentReport"
		},
		{
			"kebab": "document-search",
			"camel": "documentSearch",
			"title": "DocumentSearch"
		},
		{
			"kebab": "document-text",
			"camel": "documentText",
			"title": "DocumentText"
		},
		{
			"kebab": "document",
			"camel": "document",
			"title": "Document"
		},
		{
			"kebab": "dots-circle-horizontal",
			"camel": "dotsCircleHorizontal",
			"title": "DotsCircleHorizontal"
		},
		{
			"kebab": "dots-horizontal",
			"camel": "dotsHorizontal",
			"title": "DotsHorizontal"
		},
		{
			"kebab": "dots-vertical",
			"camel": "dotsVertical",
			"title": "DotsVertical"
		},
		{
			"kebab": "download",
			"camel": "download",
			"title": "Download"
		},
		{
			"kebab": "duplicate",
			"camel": "duplicate",
			"title": "Duplicate"
		},
		{
			"kebab": "emoji-happy",
			"camel": "emojiHappy",
			"title": "EmojiHappy"
		},
		{
			"kebab": "emoji-sad",
			"camel": "emojiSad",
			"title": "EmojiSad"
		},
		{
			"kebab": "exclamation-circle",
			"camel": "exclamationCircle",
			"title": "ExclamationCircle"
		},
		{
			"kebab": "exclamation",
			"camel": "exclamation",
			"title": "Exclamation"
		},
		{
			"kebab": "external-link",
			"camel": "externalLink",
			"title": "ExternalLink"
		},
		{
			"kebab": "eye-off",
			"camel": "eyeOff",
			"title": "EyeOff"
		},
		{
			"kebab": "eye",
			"camel": "eye",
			"title": "Eye"
		},
		{
			"kebab": "fast-forward",
			"camel": "fastForward",
			"title": "FastForward"
		},
		{
			"kebab": "film",
			"camel": "film",
			"title": "Film"
		},
		{
			"kebab": "filter",
			"camel": "filter",
			"title": "Filter"
		},
		{
			"kebab": "finger-print",
			"camel": "fingerPrint",
			"title": "FingerPrint"
		},
		{
			"kebab": "fire",
			"camel": "fire",
			"title": "Fire"
		},
		{
			"kebab": "flag",
			"camel": "flag",
			"title": "Flag"
		},
		{
			"kebab": "folder-add",
			"camel": "folderAdd",
			"title": "FolderAdd"
		},
		{
			"kebab": "folder-download",
			"camel": "folderDownload",
			"title": "FolderDownload"
		},
		{
			"kebab": "folder-open",
			"camel": "folderOpen",
			"title": "FolderOpen"
		},
		{
			"kebab": "folder-remove",
			"camel": "folderRemove",
			"title": "FolderRemove"
		},
		{
			"kebab": "folder",
			"camel": "folder",
			"title": "Folder"
		},
		{
			"kebab": "gift",
			"camel": "gift",
			"title": "Gift"
		},
		{
			"kebab": "globe-alt",
			"camel": "globeAlt",
			"title": "GlobeAlt"
		},
		{
			"kebab": "globe",
			"camel": "globe",
			"title": "Globe"
		},
		{
			"kebab": "hand",
			"camel": "hand",
			"title": "Hand"
		},
		{
			"kebab": "hashtag",
			"camel": "hashtag",
			"title": "Hashtag"
		},
		{
			"kebab": "heart",
			"camel": "heart",
			"title": "Heart"
		},
		{
			"kebab": "home",
			"camel": "home",
			"title": "Home"
		},
		{
			"kebab": "identification",
			"camel": "identification",
			"title": "Identification"
		},
		{
			"kebab": "inbox-in",
			"camel": "inboxIn",
			"title": "InboxIn"
		},
		{
			"kebab": "inbox",
			"camel": "inbox",
			"title": "Inbox"
		},
		{
			"kebab": "information-circle",
			"camel": "informationCircle",
			"title": "InformationCircle"
		},
		{
			"kebab": "key",
			"camel": "key",
			"title": "Key"
		},
		{
			"kebab": "library",
			"camel": "library",
			"title": "Library"
		},
		{
			"kebab": "light-bulb",
			"camel": "lightBulb",
			"title": "LightBulb"
		},
		{
			"kebab": "lightning-bolt",
			"camel": "lightningBolt",
			"title": "LightningBolt"
		},
		{
			"kebab": "link",
			"camel": "link",
			"title": "Link"
		},
		{
			"kebab": "location-marker",
			"camel": "locationMarker",
			"title": "LocationMarker"
		},
		{
			"kebab": "lock-closed",
			"camel": "lockClosed",
			"title": "LockClosed"
		},
		{
			"kebab": "lock-open",
			"camel": "lockOpen",
			"title": "LockOpen"
		},
		{
			"kebab": "login",
			"camel": "login",
			"title": "Login"
		},
		{
			"kebab": "logout",
			"camel": "logout",
			"title": "Logout"
		},
		{
			"kebab": "mail-open",
			"camel": "mailOpen",
			"title": "MailOpen"
		},
		{
			"kebab": "mail",
			"camel": "mail",
			"title": "Mail"
		},
		{
			"kebab": "map",
			"camel": "map",
			"title": "Map"
		},
		{
			"kebab": "menu-alt-1",
			"camel": "menuAlt1",
			"title": "MenuAlt1"
		},
		{
			"kebab": "menu-alt-2",
			"camel": "menuAlt2",
			"title": "MenuAlt2"
		},
		{
			"kebab": "menu-alt-3",
			"camel": "menuAlt3",
			"title": "MenuAlt3"
		},
		{
			"kebab": "menu-alt-4",
			"camel": "menuAlt4",
			"title": "MenuAlt4"
		},
		{
			"kebab": "menu",
			"camel": "menu",
			"title": "Menu"
		},
		{
			"kebab": "microphone",
			"camel": "microphone",
			"title": "Microphone"
		},
		{
			"kebab": "minus-circle",
			"camel": "minusCircle",
			"title": "MinusCircle"
		},
		{
			"kebab": "minus-sm",
			"camel": "minusSm",
			"title": "MinusSm"
		},
		{
			"kebab": "minus",
			"camel": "minus",
			"title": "Minus"
		},
		{
			"kebab": "moon",
			"camel": "moon",
			"title": "Moon"
		},
		{
			"kebab": "music-note",
			"camel": "musicNote",
			"title": "MusicNote"
		},
		{
			"kebab": "newspaper",
			"camel": "newspaper",
			"title": "Newspaper"
		},
		{
			"kebab": "office-building",
			"camel": "officeBuilding",
			"title": "OfficeBuilding"
		},
		{
			"kebab": "paper-airplane",
			"camel": "paperAirplane",
			"title": "PaperAirplane"
		},
		{
			"kebab": "paper-clip",
			"camel": "paperClip",
			"title": "PaperClip"
		},
		{
			"kebab": "pause",
			"camel": "pause",
			"title": "Pause"
		},
		{
			"kebab": "pencil-alt",
			"camel": "pencilAlt",
			"title": "PencilAlt"
		},
		{
			"kebab": "pencil",
			"camel": "pencil",
			"title": "Pencil"
		},
		{
			"kebab": "phone-incoming",
			"camel": "phoneIncoming",
			"title": "PhoneIncoming"
		},
		{
			"kebab": "phone-missed-call",
			"camel": "phoneMissedCall",
			"title": "PhoneMissedCall"
		},
		{
			"kebab": "phone-outgoing",
			"camel": "phoneOutgoing",
			"title": "PhoneOutgoing"
		},
		{
			"kebab": "phone",
			"camel": "phone",
			"title": "Phone"
		},
		{
			"kebab": "photograph",
			"camel": "photograph",
			"title": "Photograph"
		},
		{
			"kebab": "play",
			"camel": "play",
			"title": "Play"
		},
		{
			"kebab": "plus-circle",
			"camel": "plusCircle",
			"title": "PlusCircle"
		},
		{
			"kebab": "plus-sm",
			"camel": "plusSm",
			"title": "PlusSm"
		},
		{
			"kebab": "plus",
			"camel": "plus",
			"title": "Plus"
		},
		{
			"kebab": "presentation-chart-bar",
			"camel": "presentationChartBar",
			"title": "PresentationChartBar"
		},
		{
			"kebab": "presentation-chart-line",
			"camel": "presentationChartLine",
			"title": "PresentationChartLine"
		},
		{
			"kebab": "printer",
			"camel": "printer",
			"title": "Printer"
		},
		{
			"kebab": "puzzle",
			"camel": "puzzle",
			"title": "Puzzle"
		},
		{
			"kebab": "qrcode",
			"camel": "qrcode",
			"title": "Qrcode"
		},
		{
			"kebab": "question-mark-circle",
			"camel": "questionMarkCircle",
			"title": "QuestionMarkCircle"
		},
		{
			"kebab": "receipt-refund",
			"camel": "receiptRefund",
			"title": "ReceiptRefund"
		},
		{
			"kebab": "receipt-tax",
			"camel": "receiptTax",
			"title": "ReceiptTax"
		},
		{
			"kebab": "refresh",
			"camel": "refresh",
			"title": "Refresh"
		},
		{
			"kebab": "reply",
			"camel": "reply",
			"title": "Reply"
		},
		{
			"kebab": "rewind",
			"camel": "rewind",
			"title": "Rewind"
		},
		{
			"kebab": "rss",
			"camel": "rss",
			"title": "Rss"
		},
		{
			"kebab": "save-as",
			"camel": "saveAs",
			"title": "SaveAs"
		},
		{
			"kebab": "save",
			"camel": "save",
			"title": "Save"
		},
		{
			"kebab": "scale",
			"camel": "scale",
			"title": "Scale"
		},
		{
			"kebab": "scissors",
			"camel": "scissors",
			"title": "Scissors"
		},
		{
			"kebab": "search-circle",
			"camel": "searchCircle",
			"title": "SearchCircle"
		},
		{
			"kebab": "search",
			"camel": "search",
			"title": "Search"
		},
		{
			"kebab": "selector",
			"camel": "selector",
			"title": "Selector"
		},
		{
			"kebab": "server",
			"camel": "server",
			"title": "Server"
		},
		{
			"kebab": "share",
			"camel": "share",
			"title": "Share"
		},
		{
			"kebab": "shield-check",
			"camel": "shieldCheck",
			"title": "ShieldCheck"
		},
		{
			"kebab": "shield-exclamation",
			"camel": "shieldExclamation",
			"title": "ShieldExclamation"
		},
		{
			"kebab": "shopping-bag",
			"camel": "shoppingBag",
			"title": "ShoppingBag"
		},
		{
			"kebab": "shopping-cart",
			"camel": "shoppingCart",
			"title": "ShoppingCart"
		},
		{
			"kebab": "sort-ascending",
			"camel": "sortAscending",
			"title": "SortAscending"
		},
		{
			"kebab": "sort-descending",
			"camel": "sortDescending",
			"title": "SortDescending"
		},
		{
			"kebab": "sparkles",
			"camel": "sparkles",
			"title": "Sparkles"
		},
		{
			"kebab": "speakerphone",
			"camel": "speakerphone",
			"title": "Speakerphone"
		},
		{
			"kebab": "star",
			"camel": "star",
			"title": "Star"
		},
		{
			"kebab": "status-offline",
			"camel": "statusOffline",
			"title": "StatusOffline"
		},
		{
			"kebab": "status-online",
			"camel": "statusOnline",
			"title": "StatusOnline"
		},
		{
			"kebab": "stop",
			"camel": "stop",
			"title": "Stop"
		},
		{
			"kebab": "sun",
			"camel": "sun",
			"title": "Sun"
		},
		{
			"kebab": "support",
			"camel": "support",
			"title": "Support"
		},
		{
			"kebab": "switch-horizontal",
			"camel": "switchHorizontal",
			"title": "SwitchHorizontal"
		},
		{
			"kebab": "switch-vertical",
			"camel": "switchVertical",
			"title": "SwitchVertical"
		},
		{
			"kebab": "table",
			"camel": "table",
			"title": "Table"
		},
		{
			"kebab": "tag",
			"camel": "tag",
			"title": "Tag"
		},
		{
			"kebab": "template",
			"camel": "template",
			"title": "Template"
		},
		{
			"kebab": "terminal",
			"camel": "terminal",
			"title": "Terminal"
		},
		{
			"kebab": "thumb-down",
			"camel": "thumbDown",
			"title": "ThumbDown"
		},
		{
			"kebab": "thumb-up",
			"camel": "thumbUp",
			"title": "ThumbUp"
		},
		{
			"kebab": "ticket",
			"camel": "ticket",
			"title": "Ticket"
		},
		{
			"kebab": "translate",
			"camel": "translate",
			"title": "Translate"
		},
		{
			"kebab": "trash",
			"camel": "trash",
			"title": "Trash"
		},
		{
			"kebab": "trending-down",
			"camel": "trendingDown",
			"title": "TrendingDown"
		},
		{
			"kebab": "trending-up",
			"camel": "trendingUp",
			"title": "TrendingUp"
		},
		{
			"kebab": "truck",
			"camel": "truck",
			"title": "Truck"
		},
		{
			"kebab": "upload",
			"camel": "upload",
			"title": "Upload"
		},
		{
			"kebab": "user-add",
			"camel": "userAdd",
			"title": "UserAdd"
		},
		{
			"kebab": "user-circle",
			"camel": "userCircle",
			"title": "UserCircle"
		},
		{
			"kebab": "user-group",
			"camel": "userGroup",
			"title": "UserGroup"
		},
		{
			"kebab": "user-remove",
			"camel": "userRemove",
			"title": "UserRemove"
		},
		{
			"kebab": "user",
			"camel": "user",
			"title": "User"
		},
		{
			"kebab": "users",
			"camel": "users",
			"title": "Users"
		},
		{
			"kebab": "variable",
			"camel": "variable",
			"title": "Variable"
		},
		{
			"kebab": "video-camera",
			"camel": "videoCamera",
			"title": "VideoCamera"
		},
		{
			"kebab": "view-boards",
			"camel": "viewBoards",
			"title": "ViewBoards"
		},
		{
			"kebab": "view-grid-add",
			"camel": "viewGridAdd",
			"title": "ViewGridAdd"
		},
		{
			"kebab": "view-grid",
			"camel": "viewGrid",
			"title": "ViewGrid"
		},
		{
			"kebab": "view-list",
			"camel": "viewList",
			"title": "ViewList"
		},
		{
			"kebab": "volume-off",
			"camel": "volumeOff",
			"title": "VolumeOff"
		},
		{
			"kebab": "volume-up",
			"camel": "volumeUp",
			"title": "VolumeUp"
		},
		{
			"kebab": "wifi",
			"camel": "wifi",
			"title": "Wifi"
		},
		{
			"kebab": "x-circle",
			"camel": "xCircle",
			"title": "XCircle"
		},
		{
			"kebab": "x",
			"camel": "x",
			"title": "X"
		},
		{
			"kebab": "zoom-in",
			"camel": "zoomIn",
			"title": "ZoomIn"
		},
		{
			"kebab": "zoom-out",
			"camel": "zoomOut",
			"title": "ZoomOut"
		}
	]
}
